# Generated by Django 4.2.1 on 2023-05-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
