# Generated by Django 4.2.1 on 2023-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_album_cover_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(blank=True),
        ),
    ]
