# Generated by Django 4.2.1 on 2023-05-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_explicit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='date_uploaded',
        ),
    ]
