# Generated by Django 4.2.1 on 2023-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_song_date_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='listenings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='listenings',
            field=models.IntegerField(default=0),
        ),
    ]
