# Generated by Django 4.2.1 on 2023-05-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_duration_ms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration_ms',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
