# Generated by Django 4.2.1 on 2023-05-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='recording_file',
            field=models.FileField(blank=True, upload_to='media/uploaded_songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='recording_link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
