# Generated by Django 4.2.1 on 2023-05-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_album_cover_file_song_recording_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
