# Generated by Django 4.2.1 on 2023-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_album_cover_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='recording_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
