# Generated by Django 4.2.1 on 2023-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_album_cover_file_remove_song_recording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='recording_file',
            field=models.FileField(blank=True, upload_to='media/uploaded_songs/'),
        ),
    ]
