# Generated by Django 4.2.1 on 2023-05-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_song_recording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
