# Generated by Django 4.2.1 on 2023-05-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_album_cover_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
    ]
