# Generated by Django 4.2.1 on 2023-05-23 09:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('songs', '0013_song_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songtag',
            name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='AlbumTag',
        ),
        migrations.DeleteModel(
            name='SongTag',
        ),
    ]
