# Generated by Django 4.2.1 on 2023-05-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0014_remove_songtag_song_album_tags_delete_albumtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='songs.song'),
        ),
        migrations.DeleteModel(
            name='PlaylistElement',
        ),
    ]
