# Generated by Django 4.2.1 on 2023-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_playlist_songs_delete_playlistelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='listenings',
            field=models.IntegerField(default=0),
        ),
    ]
