# Generated by Django 4.2.1 on 2023-06-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_playlist_listenings'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
