# Generated by Django 4.2.1 on 2023-06-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_playlist_deletable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlist',
            name='Unique playlist names for each user',
        ),
    ]
