# Generated by Django 4.2.1 on 2023-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0018_remove_playlist_unique_playlist_names_for_each_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='playlist',
            name='cover_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='Unique playlist names for each user'),
        ),
    ]
