# Generated by Django 4.2.1 on 2023-06-11 12:27

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('songs', '0019_playlist_cover_file_playlist_cover_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_link',
            field=models.CharField(default='http://127.0.0.1:8000/media/default_album_cover.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='song',
            name='recording_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
