# Generated by Django 4.2.1 on 2023-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
