# Generated by Django 4.2.1 on 2023-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_pic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
