# Generated by Django 4.2.1 on 2023-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_listenings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic_link',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/media/default_pfp.jpg', max_length=255),
        ),
    ]
